version: "3"
services:

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  api:
    env_file:
      - ".env"
    platform: linux/amd64
    depends_on:
      - database
      - redis
    build:
      context: api
    ports:
      - $PORT_API_HOST:$PORT_API_CONTAINER

  worker:
    build:
        context: api
        dockerfile: Dockerfile2
    command: celery worker --app=worker.celery --loglevel=info
    volumes:
      - ./api/src:/api
    env_file:
      - ".env"
    depends_on:
      - redis


  celery_beat:
    build:
      context: api
      dockerfile: Dockerfile2
    command:  celery --app=api beat -l INFO
    volumes:
      - ./api/src:/api
    env_file:
      - ".env"
    depends_on:
      - redis

  chatbot:
    env_file:
      - ".env"
    platform: linux/amd64
    depends_on:
      - database
      - api
    links:
      - "api:api"
      - "database:database"
    build:
      context: chatbot

  database:
    image: postgres:14-alpine
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: