# Generated by Django 4.2 on 2023-10-06 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="family_members",
            field=models.ManyToManyField(
                related_name="family_members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
