# Generated by Django 4.2.6 on 2023-10-13 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_family_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="family_members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="family_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
