# Generated by Django 4.1.5 on 2023-02-12 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "symbol",
                    models.CharField(blank=True, default=None, max_length=4, null=True),
                ),
                ("user_defined", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=16)),
                (
                    "flag",
                    models.CharField(blank=True, default=None, max_length=4, null=True),
                ),
                (
                    "symbol",
                    models.CharField(blank=True, default=None, max_length=4, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonoAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mono_token", models.CharField(max_length=255, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MonoJar",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("send_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("balance", models.IntegerField()),
                ("goal", models.IntegerField()),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monobank.currency",
                    ),
                ),
                (
                    "monoaccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monobank.monoaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonoCard",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("send_id", models.CharField(max_length=255)),
                ("cashback_type", models.CharField(max_length=255)),
                ("balance", models.IntegerField()),
                ("credit_limit", models.IntegerField()),
                ("masked_pan", models.JSONField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("black", "black"), ("white", "white")], max_length=255
                    ),
                ),
                ("iban", models.CharField(max_length=255)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monobank.currency",
                    ),
                ),
                (
                    "monoaccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monobank.monoaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryMSO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mso", models.IntegerField(unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monobank.category",
                    ),
                ),
            ],
        ),
    ]
