# Generated by Django 4.2 on 2023-04-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonoTransaction",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("time", models.IntegerField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=2048, null=True),
                ),
                ("original_mcc", models.IntegerField(blank=True, null=True)),
                ("amount", models.IntegerField()),
                ("operation_amount", models.IntegerField(blank=True, null=True)),
                ("commission_rate", models.IntegerField(blank=True, null=True)),
                ("balance", models.IntegerField()),
                ("hold", models.BooleanField()),
                ("receipt_id", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monobank.monocard",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monobank.currency",
                    ),
                ),
                (
                    "mcc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monobank.categorymso",
                    ),
                ),
            ],
        ),
    ]
