# Generated by Django 4.2 on 2023-05-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0002_monotransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="monotransaction",
            name="cashback_amount",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
