# Generated by Django 4.2 on 2023-05-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0003_monotransaction_cashbackamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="monocard",
            name="comment",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
