# Generated by Django 4.2 on 2023-05-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0004_monocard_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monocard",
            name="comment",
        ),
        migrations.AddField(
            model_name="monotransaction",
            name="comment",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
