# Generated by Django 4.2 on 2023-10-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0006_alter_monojar_goal"),
    ]

    operations = [
        migrations.CreateModel(
            name="JarTransaction",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("time", models.BigIntegerField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=2048, null=True),
                ),
                ("originalMcc", models.IntegerField(blank=True, null=True)),
                ("amount", models.IntegerField()),
                ("operationAmount", models.IntegerField(blank=True, null=True)),
                ("commissionRate", models.IntegerField(blank=True, null=True)),
                ("cashbackAmount", models.IntegerField()),
                ("balance", models.IntegerField()),
                ("hold", models.BooleanField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monobank.monocard",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monobank.currency",
                    ),
                ),
                (
                    "mcc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monobank.categorymso",
                    ),
                ),
            ],
        ),
    ]
