# Generated by Django 4.2 on 2023-10-01 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0007_jartransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jartransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="monobank.monojar"
            ),
        ),
    ]
