# Generated by Django 4.2 on 2023-10-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0008_alter_jartransaction_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jartransaction",
            old_name="cashbackAmount",
            new_name="cashback_mount",
        ),
        migrations.RenameField(
            model_name="jartransaction",
            old_name="commissionRate",
            new_name="commission_rate",
        ),
        migrations.RenameField(
            model_name="jartransaction",
            old_name="operationAmount",
            new_name="operation_amount",
        ),
    ]
