# Generated by Django 4.2 on 2023-10-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0010_rename_cashback_mount_jartransaction_cashback_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jartransaction",
            old_name="originalMcc",
            new_name="original_mcc",
        ),
    ]
