# Generated by Django 4.2.6 on 2025-04-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0012_alter_monotransaction_receipt_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="jartransaction",
            name="comment",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
