# Generated by Django 4.2.6 on 2025-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0013_jartransaction_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="monojar",
            name="is_budget",
            field=models.BooleanField(default=False),
        ),
    ]
