# Generated by Django 4.2.6 on 2025-08-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0014_monojar_is_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="monocard",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="monojar",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
