name: Preview Dev Deployment

on:
  pull_request:
    branches:
      - master

env:
  V: '1'

concurrency:
  group: tests
  cancel-in-progress: false

jobs:
    test-api:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Test api
          run: |
            make test-api
    lint-api:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Lint api
          run: |
            make lint-api

