name: Preview Dev Deployment

on:
  pull_request:
    branches:
      - master
      - dev

env:
  V: '1'

concurrency:
  group: tests
  cancel-in-progress: false

jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint api
        run: |
          set -e
          make lint-api
  typecheck-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Typecheck api
        run: |
          set -e
          make typecheck-api
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test api
        run: |
          make test-api
          exit_status=$?
          if [ $exit_status -ne 0 ]; then
            echo "Tests failed with status $exit_status"
            exit $exit_status
          fi
